name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm-chart/**'
      - 'README.md'

permissions:
  contents: write  # Add this line to enable push access

jobs:

  # Step 1: Build and Test the Python Application
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest  # Assuming you are using pytest for testing

  # Step 2: Build and Push Docker Image to DockerHub
  push:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-flask-app-github-actions:${{ github.run_id }}

  # Step 3: Update Helm Chart with New Image Tag
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "'"${{ github.run_id }}"'"/' helm-chart/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "githublinkedinprojects@gmail.com"
          git config --global user.name "linkedinprojects"
          git add helm-chart/values.yaml
          git commit -m "Update tag in Helm chart for test purpose"
          git pull --rebase  # Pull before pushing to avoid conflicts
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token
